export const PATH_NAME = {
  HOME: '/',
  LOGIN: '/login',
  PROFILE: '/profile',
  ADMIN: '/admin',
  ERROR_403: '/403',
  SHIFT: '/shift',
  TEAM: '/team',
  BENEFIT: '/benefit',
  EMPLOYEE_BENEFIT: '/employee-benefit',
  DEVICES: '/devices-manager',
  WHITELIST: '/white-list',
  EMPLOYEE_SHIFT_SCHEDULE: '/shift-schedule',
  ADD_EMPLOYEE_SHIFT_SCHEDULE: '/shift-schedule/add',
  REQUEST_OFF: '/request-off',
  REQUEST_OUT: '/request-out',
  POLICY: '/policy',
  SALARY: '/salary',
  PERMISSION: '/permission',
  ADMIN_LOGS: '/system-logs',
  HOLIDAY: '/holiday',
};
