export enum PERMISSIONS {
  //TEAM
  VIEW_LIST_TEAM = 'VIEW_LIST_TEAM',
  CREATE_TEAM = 'CREATE_TEAM',
  UPDATE_TEAM = 'UPDATE_TEAM',
  DELETE_TEAM = 'DELETE_TEAM',
  // NHÂN SỰ
  VIEW_LIST_EMPLOYEE = 'VIEW_LIST_EMPLOYEE',
  CREATE_EMPLOYEE = 'CREATE_EMPLOYEE',
  UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE',
  DELETE_EMPLOYEE = 'DELETE_EMPLOYEE',
  CHANGE_STATUS_EMPLOYEE = 'CHANGE_STATUS_EMPLOYEE',
  RESET_PASSWORD_EMPLOYEE = 'RESET_PASSWORD_EMPLOYEE',
  VIEW_DETAIL_EMPLOYEE = 'VIEW_DETAIL_EMPLOYEE',
  // CA
  VIEW_LIST_SHIFF = 'VIEW_LIST_SHIFF',
  CREATE_SHIFF = 'CREATE_SHIFF',
  UPDATE_SHIFF = 'UPDATE_SHIFF',
  DELETE_SHIFF = 'DELETE_SHIFF',
  MANAGE_OUT_EARLY_LATE = 'MANAGE_OUT_EARLY_LATE',
  // LỊCH LÀM VIỆC
  VIEW_SCHEDULES = 'VIEW_SCHEDULES',
  CREATE_SCHEDULE = 'CREATE_SCHEDULE',
  DELETE_SCHEDULE = 'DELETE_SCHEDULE',
  //CHÍNH SÁCH LƯƠNG
  VIEW_BENEFIT = 'VIEW_BENEFIT',
  CREATE_BENEFIT = 'CREATE_BENEFIT',
  UPDATE_BENEFIT = 'UPDATE_BENEFIT',
  DELETE_BENEFIT = 'DELETE_BENEFIT',
  //LƯƠNG NHÂN VIÊN
  VIEW_EMPLOYEE_BENEFIT = 'VIEW_EMPLOYEE_BENEFIT',
  CREATE_EMPLOYEE_BENEFIT = 'CREATE_EMPLOYEE_BENEFIT',
  UPDATE_EMPLOYEE_BENEFIT = 'UPDATE_EMPLOYEE_BENEFIT',
  DELETE_EMPLOYEE_BENEFIT = 'DELETE_EMPLOYEE_BENEFIT',
  //QUẢN LÝ THIẾT BỊ
  VIEW_EMPLOYEE_MATERIAL = 'VIEW_EMPLOYEE_MATERIAL',
  CREATE_EMPLOYEE_MATERIAL = 'CREATE_EMPLOYEE_MATERIAL',
  DELETE_EMPLOYEE_MATERIAL = 'DELETE_EMPLOYEE_MATERIAL',
  //QUẢN LÝ IP
  VIEW_IPS = 'VIEW_IPS',
  CREATE_IP = 'CREATE_IP',
  DELETE_IP = 'DELETE_IP',
  WIEW_LOGS = 'WIEW_LOGS',
  WIEW_REQUESTS = 'WIEW_REQUESTS',
  APPROVE_REQUESTS = 'APPROVE_REQUESTS',
  VIEW_HISTORY_EMPLOYEE = 'VIEW_HISTORY_EMPLOYEE',
  //chỉ supper admin
  VIEW_SYSTEM_LOGS = 'VIEW_SYSTEM_LOGS',
  HOLIDAY = 'HOLIDAY',
}

export const ROLE_ACCOUNT = {
  BOSS: 'BOSS',
  HIGH_MANAGER: 'HIGH_MANAGER',
  MANAGER: 'MANAGER',
  LEADER: 'LEADER',
  SUPLEAD: 'SUPLEAD',
  STAFF: 'STAFF',
  ASSISTANT: 'ASSISTANT',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
};
