name: Build & Release (internal)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
          - os: macos-latest # Apple Silicon (arm64)
            platform: mac-arm64
            arch: arm64
          - os: macos-13 # Intel (x64)
            platform: mac-x64
            arch: x64
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - name: Set version from tag (strip "v")
        run: |
          npm version "${GITHUB_REF_NAME#v}" --no-git-tag-version
          node -p "require('./package.json').version"

      - name: Build & Publish (unsigned)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # GitHub PAT (repo)
          ELECTRON: 'true'
          NODE_ENV: production
          VITE_API_URL: ${{ secrets.API_URL }}
        run: |
          if [[ "${{ matrix.platform }}" == "mac-arm64" ]]; then
            npm run release -- --mac --arm64
          elif [[ "${{ matrix.platform }}" == "mac-x64" ]]; then
            npm run release -- --mac --x64
          elif [[ "${{ matrix.platform }}" == "windows" ]]; then
            npm run release -- --win
          fi
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.platform }}
          path: release/**
