name: Build & Release (internal)

defaults:
  run:
    shell: bash

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
          - os: macos-latest # Apple Silicon (arm64)
            platform: mac-arm64
            arch: arm64
          - os: macos-13 # Intel (x64)
            platform: mac-x64
            arch: x64
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - name: Set version from tag (strip "v")
        run: |
          TAG="${GITHUB_REF_NAME:-${{ github.ref_name }}}"
          VERSION="${TAG#v}"
          CURRENT="$(node -p "require('./package.json').version")"

          echo "Tag: $TAG -> version: $VERSION (current: $CURRENT)"
          if [ "$CURRENT" != "$VERSION" ]; then
            npm version "$VERSION" --no-git-tag-version
          else
            echo "Version unchanged; skipping npm version"
          fi

          echo "PKG_VERSION=$(node -p "require('./package.json').version")" >> "$GITHUB_ENV"

      - name: Build & Publish (unsigned)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # GitHub PAT (repo)
          ELECTRON: 'true'
          NODE_ENV: production
          VITE_API_URL: ${{ secrets.API_URL }}
        run: |
          if [[ "${{ matrix.platform }}" == "mac-arm64" ]]; then
            npm run release -- --mac --arm64
          elif [[ "${{ matrix.platform }}" == "mac-x64" ]]; then
            npm run release -- --mac --x64
          elif [[ "${{ matrix.platform }}" == "windows" ]]; then
            npm run release -- --win
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.platform }}
          path: release/**
